#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import re

def get_pinyin_for_word(word):
    """为英文单词生成音标"""
    # 这里使用一个简化的音标映射表
    # 实际应用中可能需要更复杂的音标生成算法或API
    pinyin_map = {
        'advanced': '|ədˈvɑːnst|',
        'adventure': '|ədˈventʃər|',
        'advertisement': '|ədˈvɜːtɪsmənt|',
        'aeroplane': '|ˈeərəpleɪn|',
        'afterwards': '|ˈɑːftəwədz|',
        'agent': '|ˈeɪdʒənt|',
        'alright': '|ɔːlˈraɪt|',
        'ambulance': '|ˈæmbjʊləns|',
        'appointment': '|əˈpɔɪntmənt|',
        'assistant': '|əˈsɪstənt|',
        'band': '|bænd|',
        'barbecue': '|ˈbɑːbɪkjuː|',
        'bath': '|bɑːθ|',
        'beginner': '|bɪˈɡɪnər|',
        'belt': '|belt|',
        'bicycle': '|ˈbaɪsɪkl|',
        'blanket': '|ˈblæŋkɪt|',
        'blond': '|blɒnd|',
        'boil': '|bɔɪl|',
        'bookshelf': '|ˈbʊkʃelf|',
        'bookshop': '|ˈbʊkʃɒp|',
        'boot': '|buːt|',
        'boots': '|buːts|',
        'brake': '|breɪk|',
        'brilliant': '|ˈbrɪljənt|',
        'burger': '|ˈbɜːɡər|',
        'businessman': '|ˈbɪznɪsmən|',
        'businesswoman': '|ˈbɪznɪswʊmən|',
        'butter': '|ˈbʌtər|',
        'café': '|ˈkæfeɪ|',
        'camel': '|ˈkæml|',
        'campsite': '|ˈkæmpsaɪt|',
        'canal': '|kəˈnæl|',
        'career': '|kəˈrɪər|',
        'carpet': '|ˈkɑːpɪt|',
        'case': '|keɪs|',
        'cash': '|kæʃ|',
        'castle': '|ˈkɑːsl|',
        'cathedral': '|kəˈθiːdrəl|',
        'centimetre': '|ˈsentɪmiːtər|',
        'channel': '|ˈtʃænl|',
        'chat': '|tʃæt|',
        'chatroom': '|ˈtʃætruːm|',
        'cheers': '|tʃɪəz|',
        'cheese': '|tʃiːz|',
        'chemist': '|ˈkemɪst|',
        'cheque': '|tʃek|',
        'chips': '|tʃɪps|',
        'church': '|tʃɜːtʃ|',
        'circus': '|ˈsɜːkəs|',
        'classical': '|ˈklæsɪkl|',
        'cleaner': '|ˈkliːnər|',
        'click': '|klɪk|',
        'closed': '|kləʊzd|',
        'clown': '|klaʊn|',
        'colleague': '|ˈkɒliːɡ|',
        'comb': '|kəʊm|',
        'cooker': '|ˈkʊkər|',
        'costume': '|ˈkɒstjuːm|',
        'credit': '|ˈkredɪt|',
        'crowded': '|ˈkraʊdɪd|',
        'cupboard': '|ˈkʌbəd|',
        'curtains': '|ˈkɜːtnz|',
        'cycle': '|ˈsaɪkl|',
        'dancer': '|ˈdɑːnsər|',
        'dancing': '|ˈdɑːnsɪŋ|',
        'delay': '|dɪˈleɪ|',
        'delayed': '|dɪˈleɪd|',
        'dentist': '|ˈdentɪst|',
        'digital': '|ˈdɪdʒɪtl|',
        'dinosaur': '|ˈdaɪnəsɔːr|',
        'diploma': '|dɪˈpləʊmə|',
        'disco': '|ˈdɪskəʊ|',
        'discount': '|ˈdɪskaʊnt|',
        'dolphin': '|ˈdɒlfɪn|',
        'dot': '|dɒt|',
        'download': '|ˈdaʊnləʊd|',
        'downstairs': '|ˈdaʊnsteəz|',
        'dragon': '|ˈdræɡən|',
        'drawing': '|ˈdrɔːɪŋ|',
        'driving': '|ˈdraɪvɪŋ|',
        'drum': '|drʌm|',
        'dvd': '|ˌdiː viː ˈdiː|',
        'earn': '|ɜːn|',
        'electric': '|ɪˈlektrik|',
        'electricity': '|ɪˌlekˈtrɪsəti|',
        'entrance': '|ˈentrəns|',
        'euro': '|ˈjʊərəʊ|',
        'examination': '|ɪɡˌzæmɪˈneɪʃn|',
        'exhibition': '|ˌeksɪˈbɪʃn|',
        'exit': '|ˈeksɪt|',
        'explore': '|ɪkˈsplɔːr|',
        'explorer': '|ɪkˈsplɔːrər|',
        'extra': '|ˈekstrə|',
        'fashion': '|ˈfæʃn|',
        'fishing': '|ˈfɪʃɪŋ|',
        'flight': '|flaɪt|',
        'fog': '|fɒɡ|',
        'foggy': '|ˈfɒɡi|',
        'footballer': '|ˈfʊtbɔːlər|',
        'fried': '|fraɪd|',
        'fry': '|fraɪ|',
        'furniture': '|ˈfɜːnɪtʃər|',
        'garage': '|ˈɡærɑːʒ|',
        'gas': '|ɡæs|',
        'glasses': '|ˈɡlɑːsɪz|',
        'golf': '|ɡɒlf|',
        'got': '|ɡɒt|',
        'gram': '|ɡræm|',
        'grand': '|ɡrænd|',
        'grandad': '|ˈɡrændæd|',
        'grandchild': '|ˈɡræntʃaɪld|',
        'grandma': '|ˈɡrænmɑː|',
        'grandpa': '|ˈɡrænpɑː|',
        'grill': '|ɡrɪl|',
        'grilled': '|ɡrɪld|',
        'guest-house': '|ˈɡest haʊs|',
        'guidebook': '|ˈɡaɪdbʊk|',
        'guy': '|ɡaɪ|',
        'hairdresser': '|ˈheədresər|',
        'hairdryer': '|ˈheədraɪər|',
        'hallo': '|həˈləʊ|',
        'heating': '|ˈhiːtɪŋ|',
        'helicopter': '|ˈhelɪkɒptər|',
        'hip': '|hɪp|',
        'hockey': '|ˈhɒki|',
        'holidays': '|ˈhɒlɪdeɪz|',
        'hop': '|hɒp|',
        'hours': '|ˈaʊəz|',
        'indoors': '|ˌɪnˈdɔːz|',
        'insect': '|ˈɪnsekt|',
        'instructions': '|ɪnˈstrʌkʃnz|',
        'insurance': '|ɪnˈʃʊərəns|',
        'interested': '|ˈɪntrəstɪd|',
        'jam': '|dʒæm|',
        'jeans': '|dʒiːnz|',
        'journalist': '|ˈdʒɜːnəlɪst|',
        'kilo': '|ˈkiːləʊ|',
        'kilometre': '|ˈkɪləmiːtər|',
        'laptop': '|ˈlæptɒp|',
        'leather': '|ˈleðər|',
        'lemonade': '|ˌleməˈneɪd|',
        'licence': '|ˈlaɪsns|',
        'lights': '|laɪts|',
        'litre': '|ˈliːtər|',
        'living': '|ˈlɪvɪŋ|',
        'lorry': '|ˈlɒri|',
        'lots': '|lɒts|',
        'luggage': '|ˈlʌɡɪdʒ|',
        'married': '|ˈmærid|',
        'mechanic': '|mɪˈkænɪk|',
        'metre': '|ˈmiːtər|',
        'midnight': '|ˈmɪdnaɪt|',
        'mineral': '|ˈmɪnərəl|',
        'mobile': '|ˈməʊbaɪl|',
        'monthly': '|ˈmʌnθli|',
        'motorbike': '|ˈməʊtəbaɪk|',
        'motorway': '|ˈməʊtəweɪ|',
        'mp3': '|ˌem piː ˈθriː|',
        'mum': '|mʌm|',
        'nationality': '|ˌnæʃəˈnæləti|',
        'newsagent': '|ˈnjuːzeɪdʒənt|',
        'nowhere': '|ˈnəʊweər|',
        'occupation': '|ˌɒkjəˈpeɪʃn|',
        'okay': '|əʊˈkeɪ|',
        'omelette': '|ˈɒmlət|',
        'onion': '|ˈʌnjən|',
        'opera': '|ˈɒpərə|',
        'outdoor': '|ˈaʊtdɔːr|',
        'outdoors': '|ˌaʊtˈdɔːz|',
        'pack': '|pæk|',
        'painter': '|ˈpeɪntər|',
        'parrot': '|ˈpærət|',
        'pasta': '|ˈpæstə|',
        'pen-friend': '|ˈpen frend|',
        'pence': '|pens|',
        'penny': '|ˈpeni|',
        'pepper': '|ˈpepər|',
        'per': '|pɜːr|',
        'petrol': '|ˈpetrəl|',
        'pharmacy': '|ˈfɑːməsi|',
        'photograph': '|ˈfəʊtəɡrɑːf|',
        'photographer': '|fəˈtɒɡrəfər|',
        'photography': '|fəˈtɒɡrəfi|',
        'piano': '|piˈænəʊ|',
        'pillow': '|ˈpɪləʊ|',
        'pizza': '|ˈpiːtsə|',
        'plate': '|pleɪt|',
        'platform': '|ˈplætfɔːm|',
        'pm': '|ˌpiː ˈem|',
        'pop': '|pɒp|',
        'poster': '|ˈpəʊstər|',
        'practise': '|ˈpræktɪs|',
        'programme': '|ˈprəʊɡræm|',
        'purse': '|pɜːs|',
        'quiz': '|kwɪz|',
        'racket': '|ˈrækɪt|',
        'raincoat': '|ˈreɪnkəʊt|',
        'rainforest': '|ˈreɪnfɒrɪst|',
        'reggae': '|ˈreɡeɪ|',
        'rent': '|rent|',
        'restaurant': '|ˈrestrɒnt|',
        'rock': '|rɒk|',
        'rugby': '|ˈrʌɡbi|',
        'sailing': '|ˈseɪlɪŋ|',
        'salad': '|ˈsæləd|',
        'sandwich': '|ˈsænwɪtʃ|',
        'sauce': '|sɔːs|',
        'sausage': '|ˈsɒsɪdʒ|',
        'screen': '|skriːn|',
        'shopping': '|ˈʃɒpɪŋ|',
        'shorts': '|ʃɔːts|',
        'shower': '|ˈʃaʊər|',
        'singer': '|ˈsɪŋər|',
        'skateboard': '|ˈskeɪtbɔːd|',
        'skiing': '|ˈskiːɪŋ|',
        'snowboarding': '|ˈsnəʊbɔːdɪŋ|',
        'soap': '|səʊp|',
        'soccer': '|ˈsɒkər|',
        'socks': '|sɒks|',
        'soup': '|suːp|',
        'spend': '|spend|',
        'spoon': '|spuːn|',
        'sport': '|spɔːt|',
        'sports': '|spɔːts|',
        'spring': '|sprɪŋ|',
        'stadium': '|ˈsteɪdiəm|',
        'station': '|ˈsteɪʃn|',
        'stomach': '|ˈstʌmək|',
        'storm': '|stɔːm|',
        'stormy': '|ˈstɔːmi|',
        'straight': '|streɪt|',
        'street': '|striːt|',
        'studies': '|ˈstʌdiz|',
        'suitcase': '|ˈsuːtkeɪs|',
        'summer': '|ˈsʌmər|',
        'sunglasses': '|ˈsʌnɡlɑːsɪz|',
        'sunny': '|ˈsʌni|',
        'supermarket': '|ˈsuːpəmɑːkɪt|',
        'swimming': '|ˈswɪmɪŋ|',
        'tablet': '|ˈtæblət|',
        'taxi': '|ˈtæksi|',
        'telephone': '|ˈtelɪfəʊn|',
        'television': '|ˈtelɪvɪʒn|',
        'tennis': '|ˈtenɪs|',
        'text': '|tekst|',
        'theatre': '|ˈθɪətər|',
        'thunder': '|ˈθʌndər|',
        'thunderstorm': '|ˈθʌndəstɔːm|',
        'ticket': '|ˈtɪkɪt|',
        'tiger': '|ˈtaɪɡər|',
        'toast': '|təʊst|',
        'today': '|təˈdeɪ|',
        'tomorrow': '|təˈmɒrəʊ|',
        'tonight': '|təˈnaɪt|',
        'toothbrush': '|ˈtuːθbrʌʃ|',
        'toothpaste': '|ˈtuːθpeɪst|',
        'tourist': '|ˈtʊərɪst|',
        'towel': '|ˈtaʊəl|',
        'tower': '|ˈtaʊər|',
        'town': '|taʊn|',
        'traffic': '|ˈtræfɪk|',
        'train': '|treɪn|',
        'trainer': '|ˈtreɪnər|',
        'trainers': '|ˈtreɪnəz|',
        'tram': '|træm|',
        'travel': '|ˈtrævl|',
        'tree': '|triː|',
        'trip': '|trɪp|',
        'trousers': '|ˈtraʊzəz|',
        'truck': '|trʌk|',
        'umbrella': '|ʌmˈbrelə|',
        'underground': '|ˈʌndəɡraʊnd|',
        'upstairs': '|ˌʌpˈsteəz|',
        'video': '|ˈvɪdiəʊ|',
        'video recorder': '|ˈvɪdiəʊ rɪˈkɔːdər|',
        'view': '|vjuː|',
        'village': '|ˈvɪlɪdʒ|',
        'waiter': '|ˈweɪtər|',
        'waitress': '|ˈweɪtrəs|',
        'warm': '|wɔːm|',
        'washing machine': '|ˈwɒʃɪŋ məˈʃiːn|',
        'weather': '|ˈweðər|',
        'week': '|wiːk|',
        'weekend': '|ˌwiːkˈend|',
        'welcome': '|ˈwelkəm|',
        'well': '|wel|',
        'west': '|west|',
        'western': '|ˈwestən|',
        'wheel': '|wiːl|',
        'wheelchair': '|ˈwiːltʃeər|',
        'whisper': '|ˈwɪspər|',
        'white': '|waɪt|',
        'wind': '|wɪnd|',
        'windy': '|ˈwɪndi|',
        'winter': '|ˈwɪntər|',
        'woman': '|ˈwʊmən|',
        'women': '|ˈwɪmɪn|',
        'wonderful': '|ˈwʌndəfl|',
        'wood': '|wʊd|',
        'wool': '|wʊl|',
        'woollen': '|ˈwʊlən|',
        'work': '|wɜːk|',
        'worker': '|ˈwɜːkər|',
        'world': '|wɜːld|',
        'worry': '|ˈwʌri|',
        'worse': '|wɜːs|',
        'worst': '|wɜːst|',
        'would': '|wʊd|',
        'write': '|raɪt|',
        'writer': '|ˈraɪtər|',
        'writing': '|ˈraɪtɪŋ|',
        'wrong': '|rɒŋ|',
        'year': '|jɪər|',
        'yellow': '|ˈjeləʊ|',
        'yesterday': '|ˈjestədeɪ|',
        'young': '|jʌŋ|',
        'youth': '|juːθ|',
        'zoo': '|zuː|'
    }
    
    # 查找单词的音标
    word_lower = word.lower()
    if word_lower in pinyin_map:
        return pinyin_map[word_lower]
    else:
        # 如果没有找到，返回一个基于单词的简单音标
        return f"|{word_lower}|"

def update_pinyin():
    """更新missing_words.json中的pinyin字段"""
    
    print("正在读取 missing_words.json...")
    with open('missing_words.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    print(f"读取到 {len(data)} 个单词")
    
    # 更新每个单词的pinyin字段
    for i, word_entry in enumerate(data):
        word = word_entry['character']
        pinyin = get_pinyin_for_word(word)
        data[i]['pinyin'] = pinyin
        print(f"更新 {i+1:3d}/{len(data)}: {word} -> {pinyin}")
    
    # 保存更新后的文件
    with open('missing_words.json', 'w', encoding='utf-8') as f:
        f.write('[\n')
        for i, entry in enumerate(data):
            line = json.dumps(entry, ensure_ascii=False, separators=(',', ':'))
            if i < len(data) - 1:
                line += ','
            f.write(line + '\n')
        f.write(']\n')
    
    print(f"\n已更新 {len(data)} 个单词的音标")
    print("文件已保存为 missing_words.json")

if __name__ == "__main__":
    update_pinyin() 